name: gcmobile
description: Gesture Controller for Liquid Galaxy

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  tflite: 1.0.6
  camera: 0.5.8+2
  image: 2.1.12
  flutter_socket_io: 0.6.0
  # speech_to_text: 2.3.0

dev_dependencies:
  flutter_launcher_icons: 0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_white_1024_margin.png"
  adaptive_icon_foreground: "assets/images/icon_white_1024_margin.png"
  adaptive_icon_background: "#000000"


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/poses/
  - assets/mobilenet_v1_1.0_224.tflite
  - assets/posenet_mv1_075_float_from_checkpoints.tflite
